name: 'small_door'
version: '1.0.0'
config-version: 2

profile: 'small_door'

model-paths: ["models"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  date_spine_start: '2015-01-01'
  date_spine_end: '2030-01-01'

models:
  small_door:
    staging:
      +materialized: view
    ref:
      +materialized: table
    marts:
      +materialized: table
    analysis:
      +materialized: table
